name: Coverage Report

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  report:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Use Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "20"
      - run: npm ci
      - name: Generate coverage report
        run: npm run coverage
